version: '3'
services:
  snippet-box:
    image: pawelmalak/snippet-box:latest
    container_name: snippet-box
    volumes:
      - ${APP_DATA_DIR}/snippet-box-data:/app/data
    ports:
      - 5005:5000
    restart: unless-stopped
