---
# Shaarli - Self-hosted bookmarking service
version: '3'
services:
  shaarli:
    image: shaarli/shaarli:latest
    container_name: shaarli
    ports:
      - "8484:80" # Default port 80 exposed to 5023
    volumes:
      - ./shaarli/data:/var/www/shaarli/data # Persistent data storage
    environment:
      - TZ=UTC # Set your timezone
    restart: unless-stopped
